### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by alvarosaurus** [FUB-HCC/IKON-ontology#2]
Hi,

die Museums-PR hat entschieden, wir sollen die URI 'museumfuernaturkunde.berlin' nutzen. Vielleicht auch für den Namensraum der Ontologie relevant? Wenn nicht, dann ignorieren.

**Comment by joetm** [comment]
Das soll letztendlich auf einem Namespace des Museums laufen, ja.
Für die Entwicklung werde ich jedoch zunächst alle Namespaces auf Github setzen.

**Comment by alvarosaurus** [comment]
Die Ontologie ist jetzt auf:
http://ikon.code.naturkundemuseum.berlin/ontologies/ikon.owlNS: 

wenn ich mich nicht irre, wäre der entsprechender Namensraum 
http://ikon.code.naturkundemuseum.berlin/ontologies#

könntet ihr bitte die URIs der Attribute in der Ontologie anpassen?
Ich könnte dann versuchen, die Attribute im Wiki mit deren entsprechenden URI zu annotieren.
